/* Autogenerated with DRAKON Editor 1.11 */
#ifndef TEA_H50899
#define TEA_H50899

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

int DecryptCBC(
    unsigned char *dst,
    unsigned char *src,
    size_t len,
    unsigned char iv[8],
    unsigned char key[16]
);

void EncryptCBC(
    unsigned char *dst,
    unsigned char *src,
    size_t len,
    unsigned char iv[8],
    unsigned char key[16]
);

size_t PaddedLength(
    size_t len
);

int main(void);


#endif

